project:
  type: manuscript

manuscript:
  article: index.qmd

execute:
  freeze: auto

format:
  html:
    toc: true
    fig-align: center
    lang: en
    number-sections: true
    toc-expand: 2
  pdf:
    toc: false
    fig-align: center
    lang: en
    number-sections: true
    papersize: A4
    pdf-engine: xelatex 
  docx:
    toc: false
    fig-align: center
    lang: en
    number-sections: true
    highlight-style: github
    reference-doc: ./docx/Design_Challenge_template.docx

bibliography: references.bib

