project:
  type: book
  output-dir: _book

book:
  title: "Assessing the feasibility of developing and taping-out an analog block for LED driver control using IHP-Open-PDK and IIC-OSIC-TOOLS"
  author:
    - name: Priyanka Toyni
      orcid: 
      email: ptoyni@hs-bremen.de
      corresponding: true
      roles: "Lead author"
      affiliation:
        - name: Hochschule Bremen - City University of Applied Sciences (HSB)
          city: Bremen
          state: Germany
          url: https://www.hs-bremen.de  
    - name: Hrishikesh Pangavhane
      orcid: 
      email: hpangavhane@hs-bremen.de
      corresponding: true
      roles: "Lead author"

  date: last-modified
  license: "Apache-2.0 license"

  reader-mode: true

  page-footer:
    left: |
      Assessing the feasibility of developing and taping-out an analog block for LED driver control using IHP-Open-PDK and IIC-OSIC-TOOLS.
    right: |
      This book was built with <a href="https://quarto.org/">Quarto</a>.
  # cover-image: images/hsb-logo.png
  # favicon: images/hsb-logo.png
  site-url: https://ptoyni.github.io/thesis_hp/
  repo-url: https://github.com/ptoyni/thesis_hp
  repo-branch: main
  repo-actions: [edit,issue]
  downloads: [pdf,epub]

  chapters:
    - index.qmd
    # - content/Abstract.qmd
    - content/_sec_introduction.qmd
    - content/_sec_Requirements_AES.qmd
    - part: Circuit Design
      chapters:
        - content/_sec_OTA_design.qmd   
        - content/_sec_cornersimulations.qmd   
    - part: Physical Design 
      chapters:
        - content/_sec_into_layout.qmd
        - content/_sec_OTA_layout.qmd
        - content/_sec_DRC.qmd
        - content/_sec_LVS.qmd
        - content/_sec_parasitics_prevention.qmd
        - content/_sec_layout_finalsteps.qmd
    - part: Post-Layout Simulation
      chapters:
        - content/_sec_postlayout_simulation.qmd
        - content/_sec_OTA_pex.qmd
    - references.qmd
    
  appendices:
    - content/_appendix_A.qmd
    - content/_appendix_B.qmd
    - content/_appendix_C.qmd

  output-file: "thesis_hp"


# Bibliography
bibliography: _bibliography/references.bib
csl: _bibliography/ieee.csl

number-sections: true
highlight-style: github

format:
  html:
    theme: flatly
    # number-sections: true
    # highlight-style: github

  # epub:
  #   theme: flatly
  #   number-sections: true
  #   highlight-style: github

  pdf:
    documentclass: scrbook
    keep-tex: true

    # Table of Contents
    toc: true
    lof: true
    lot: true

    # Setup page layout
    geometry: 
      - top=30mm
      - left=20mm
      - heightrounded
    hyperrefoptions:
      - linktoc=all
    colorlinks: true
    linkcolor: "blue" 

    # Fonts
    mainfont: "Calibri"

  epub:
    theme: flatly
    # documentclass: uoe-thesis-template
    # classoption: [twoside]
    # papersize: a4
    

    # template-partials:
    # - frontmatter/title.tex
    # - frontmatter/before-body.tex
    # - frontmatter/toc.tex
    # include-in-header:
    # - frontmatter/header.tex
    
college: Hochschule Bremen - City University of Applied Sciences
degree: Master of Science (M.Sc.)
year: 2025

supervisors: |
  Prof. Dr.-Ing. M. Meiners
  Prof. Dr. (PhD) S. Peik

